- R/metadata.R
allows for multiple first names for same author (middle name use common in academic literature) and still have bibtex citation record formatted appropriately .
Previously yaml header:
```yaml
author:
- name: Nicolas PJ Coutin
```
would result in the bibtex citation record to be rendered as:
```
@misc(coutin2017the,
author = {c("Coutin, Nicolas", "Coutin,PJ") and Nislow, Corey},
title = {The dark matter of personalized medicine: Non–genetic variation},
url = {http://med-fom-ubcmj.sites.olt.ubc.ca/files/2017/08/CoutinNislow-PROOF.pdf},
year = {2017}
}
```
Instead of:
```
@misc(coutin2017the,
author = {Coutin, Nicolas PJ and Nislow, Corey},
title = {The dark matter of personalized medicine: Non–genetic variation},
url = {http://med-fom-ubcmj.sites.olt.ubc.ca/files/2017/08/CoutinNislow-PROOF.p …
```
> collapse multiple first names together

- R/appendices.R
bibtex record should start with `{` character not `(` to match closing `}` in generated citation record in appendix.
> format bibtex citation with  correct { not (

- NEWS.md
- R/collections.R
- R/sitemap.R
Fix for https://github.com/rstudio/distill/issues/33, adds support for RSS content with a `_site.yml` like:
```
name: "blog"
rss:
full_content: TRUE
```
See for instance [_site.yml#L13-L14](https://github.com/rstudio/pins/blob/master/blog/_site.yml#L13-L14) which renders as [index.xml](https://rstudio.github.io/pins/blog/index.xml) / [preview](https://simplepie.org/demo/?feed=https%3A%2F%2Frstudio.github.io%2Fpins%2Fblog%2Findex.xml).
It also adds supports for [category](https://www.w3schools.com/xml/rss_tag_category_item.asp) elements which some feeds require.
> Support full content in RSS feeds 

- NEWS.md
- R/collections.R
- R/sitemap.R
Follow up to https://github.com/rstudio/distill/pull/111.
Some blog aggregators like r-bloggers, do not a allow base64 encoded images. This PR adds relative images when `rss/full_content` is set in the `_site.yml` configuration file.
See for instance: https://rstudio.github.io/pins/blog/index.xml
> Avoid base64 images when RSS uses full content

- R/sitemap.R
Follow up to https://github.com/rstudio/distill/pull/114,
Some sites, like r-bloggers, require full image URLs to render properly: https://www.r-bloggers.com/pins-0-3-azure-gcloud-and-s3/
> Use full images in RSS content

- R/collections.R
When upgrading the tensorflow blog to support r-bloggers, it showed that current RSS categories functionality in distill, do not work with existing RSS. Fix here is to remove all the previous categories when generating the per-category RSS and then adding only the categories which match the category being built.
This fix only affects blogs using RSS feeds with `categories` being specified, which is probably just `pins` and now the `tensorflow` blog.
> Support rss categories for blogs that already use rss

- inst/rmarkdown/templates/distill_article/resources/navbar.html
- inst/rmarkdown/templates/distill_article/resources/search.html
Hi @jjallaire,
I believe I found both templates where the navbar hex color was specified as `#455a64` and updated to match the current upper navbar for Distill <https://distill.pub/>: `#0F2E3D`
I unfortunately cannot re-render the docs site without seeing file path errors (opening up `docs.Rproj` and trying to build the site via the build pane or `rmarkdown::render()`). If there is a trick there, I'm happy to re-render the docs site too.
Thanks!
Alison
> Navbar hex

- docs/_common/distill_basics.Rmd
There was a call to `knitr::include_graphics()` with an absolute file path- changing it to relative allowed me to build the `docs/` site locally and in a GitHub Action 🎉
> make the path relative for include_graphics

- inst/rmarkdown/templates/distill_article/resources/base-style.css
- inst/rmarkdown/templates/distill_article/resources/base-variables.css
Hi @jjallaire,
On a visual test, I'm exactly replicating the default Distill article template. 
Next steps:
+ Add variables/styles for the default website/blog styles. For adding variables/styles to customize the [navbar](https://rstudio.github.io/distill/website.html#theming) for example, shall I add on to these two CSS files? 
+ Add docs for going deeper into customizing font families, since here we focused on font color and sizing.
> Add default values for base-variables.css and base-style.css to read them in

- inst/rmarkdown/templates/distill_article/resources/base-style.css
- inst/rmarkdown/templates/distill_article/resources/base-variables.css
Hi @jjallaire,
I'm reasonably happy with these additional CSS variables, and needed to adapt some of the base styles to make them all work well with the blog listing pages. I'm unsure where to actually put these new variables, because I think users may be confused and/or overwhelmed if they create an article and see the additional website variables populate in the `theme.css`. Marking this PR as a draft if you can advise!
Alison
> Add site themes

- R/sitemap.R
Running `rmarkdown::render_site()` under the https://github.com/rstudio/ai-blog repo does not generate the RSS feed.
This fix searches for the active post being rendered and matches the `article$path` with the existing local path to the Rmd being generated.
Fix seems to work fine even when using `rmarkdown::render_site(input_path = "../ai-blog")`, likely due to `rmarkdown` setting a consistent path while building the site.
> Support rendering rss on render_site()

- R/distill_article.R
- inst/rmarkdown/templates/distill_article/resources/base-variables.css
Hi @jjallaire,
Using [`htmltools::includeCSS()`](https://github.com/rstudio/htmltools/blob/master/R/tags.R#L1385-L1392) instead of `themeStyle()` includes all the dependencies from a combined `@import` request to the Google Font API. Here is an example of the request that now works when added at the top of my `theme.css`:
```
* Optional: embed custom fonts here with `@import`        */
@import url('https://fonts.googleapis.com/css2?family=DM+Mono&family=DM+Serif+Text&display=swap');
```
In the current dev version, here is what I see (the DM Serif Text font is not imported or applied to the headers; in testing, the first font is the only one that imports):
With this PR, I can use the second font in my import request:
This works, but I would appreciate your review to make sure there are no …
> Support importing multiple fonts in a single @import request

- inst/rmarkdown/templates/distill_article/resources/arrow.theme
- inst/rmarkdown/templates/distill_article/resources/base-style.css
To the base styles to get navbar fonts to match when a link vs dropdown menu. See: https://athanasiamo.github.io/talks/
Also small tweaks to `arrow.theme` (cc @cderv)
> Small tweaks

- R/theme.R
closes issue #235 and makes some improvements in formatting
current behavior:
```
create_theme("larug")
#> v Created CSS file at theme.css
#> o TODO: Customize it to suit your needs
#> o TODO: Add 'theme' entry to your`site/article YAML
#> 
#> See docs at https://rstudio.github.io/distill/website.html#theming
```
new behavior:
```
> create_theme()
v Created CSS file at theme.css 
o TODO: Customize it to suit your needs 
o TODO: Add 'theme: theme.css' to your site or article YAML 
See docs at https://rstudio.github.io/distill/website.html#theming
> create_theme("larug")
v Created CSS file at larug.css 
o TODO: Customize it to suit your needs 
o TODO: Add 'theme: larug.css' to your site or article YAML 
See docs at https://rstudio.github.io/distill/website.html#theming
```
> create_theme() prints correct theme name argument, if not theme.css

- NEWS.md
- R/distill_article.R
This should fix #214 
The issue is related to Pandoc - see https://github.com/rstudio/rmarkdown/issues/1976#issuecomment-741908329
This is a quick fix on **distill** side as `rmarkdown::pandoc_path_arg()` was used directly.
> remove use of pandoc_path_arg for highlight theme

- DESCRIPTION
- NEWS.md
- R/import.R
This is missing to fix #215 
It was reported after the initial fix in the community 
https://community.rstudio.com/t/issues-with-distill-import-post-404-error/91382/4
I think the default branch should retrieve from the url and not always from rstudio/distill
> find default branch from url's owner and repo when importing a post

- inst/rmarkdown/templates/distill_article/resources/navbar.html
Hi @jjallaire -
This is a bit of a quick fix. I imagine javascript could be a better solution at some point, but it works 😉 
Embedded postcard: https://apreshill.github.io/postcard/about.html
Non-embedded postcard: https://apreshill.github.io/postcard/jolla-about/jolla-about.html
(also demo version: https://seankross.com/postcards-templates/jolla/)
> override bootstrap viewport to move postcard content closer to top nav

- docs/blog.Rmd
- docs/website.Rmd
… in building the site.
The relevant PR I created for `rmarkdown` is here https://github.com/rstudio/rmarkdown/pull/1996
This will exclude the renv directory so that building the site does not copy it to the publish directory.
You might want to wait with approving this PR until the change is in the `rmarkdown` version used by distill.
> Update documentation to reflect PR in rmarkdown to exclude renv directory

- docs/figures.Rmd
In the static figures external content example at the moment there is no comma between fig.cap and out.extra so the example wouldn't run.
> Add comma so static external would work

- R/utils.R
@cderv Does this look like the right fix for the first issue?
LMK if you are able to reproduce the `read_xml.character` error.
> Use "English" for LC_TIME on windows

- R/create.R
Previously, if author was specified in `create_post()`, it was inserted without the `author: ` prefix in the YAML, giving an invalid header.
That is, `create_post('My title', author = 'John Smith')` would give a header of the form
```yaml
---
title: "My title"
description: |
A short description of the post.
John Smith
date: 01-26-2021
output:
distill::distill_article:
self_contained: false
---
```
Also: the default month-day-year date formatting is not a standard used or understood by most of the world so I changed it to the more universal year-month-day format.
After both these fixes, the expected output is returned:
```yaml
---
title: "My title"
description: |
A short description of the post.
author: John Smith
date: 2021-01-26
output:
distill::distill_article:
self_contained: false
--- …
```
> Fix author YAML and date formatting in create_post

- R/appendices.R
- R/create.R
By default, a "References" section is generated in the footer if we specify a bibliography in an external `.bib` file and refer to it from the `bibliography` YAML field, but not if we manually add *inline* references to the `references` field of the header, as described at the start of https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html. This commit aims to fix that.
For example, the following article does not get a proper **References** section in the footer unless this fix is applied.
```markdown
---
title: "test"
description: |
A short description of the post.
author:
- name: Unknown
date: 01-26-2021
references:
- id: test
author: Author Name
title: Example article reference title
type: article-journal
issued:
year: 2021
DOI: 00000001
container-title: Nature …
```
> Add support for references specified within YAML

- R/create.R
Prevent `author: author:` if author is not explictly specified, but fallback inserts an author in an existing post.
> Fix another create_post author edge case

- DESCRIPTION
- R/utils.R
This will fix #315
The version of **lubridate** with a fix is now on CRAN. The workaround is no more needed.
> Use CRAN lubridate and remove workaround

- NEWS.md
- R/navigation.R
- R/utils.R
Fix for https://github.com/rstudio/distill/issues/98
@cderv Could you review?
> Fix issue w/ UTF-8 encoded characters in site _footer.html

- R/collections.R
fix for https://github.com/rstudio/distill/issues/308.
add Encoding(somthing) <- "UTF-8" after readChar function.
> add Encoding tag UTF8 for html_content and listing_html

- docs/_common/distill_basics.Rmd
it will be parsed with `lubridate::ymd` if `lubridate::mdy` fails. 
This will complement fix for #238 
@apreshill do you think this is the last part missing ? 
Also do you know if the doc website is built automatically
> date can be formatted as Year, Month, day

- DESCRIPTION
- NEWS.md
- R/utils.R
This should finally fix #315 
lubridate 1.7.10 release on CRAN should contain the remaining part of the fix for the TZDIR issue on MacOS which causes parsing error.
> require lubridate 1.7.10 for the fix w/ timezone db on MacOS

- docs/website.Rmd
- docs/website.html
Hi @jjallaire -
I believe the latest version of rmarkdown on CRAN means that these docs now all depend on CRAN versions of the packages, so I updated this section of the docs:
https://rstudio.github.io/distill/website.html#alternate-formats
Alison
> all CRAN versions now work for embedding alternate formats in websites

- DESCRIPTION
- NEWS.md
- inst/rmarkdown/templates/distill_article/resources/listing.html
This fixes #331 
When catégories have special caractère which are URI encoded in the location hash, JS script needs to decode the URI in order to filter the listing page and update the content.
> categories needs to be URI decoded before filtering listing

- NEWS.md
- R/collections.R
This fixes #148 
Tested with this code: 
````r
library(distill)
dir_name <- "Oh (No)"
dir.create(tmp_dir <- tempfile())
withr::with_tempdir({
create_blog(dir_name, title = "Oh No", edit = FALSE)
})
rstudioapi::restartSession()
pkgload::load_all(".")
dir_name <- "Oh (No)"
dir.create(tmp_dir <- tempfile())
withr::with_tempdir({
create_blog(dir_name, title = "Oh No", edit = FALSE)
})
````
> use xfun::relative_path to get article relative path to site_dir

- inst/rmarkdown/templates/distill_article/resources/arrow.theme
Preview of how the syntax highlighting will look with these tweaks & downlit turned off:
https://apreshill.github.io/rmda11y/arrow.html
> Tweak arrow.theme for non-downlit syntax highlighting

- R/import.R
related to #344 
I see a few users trying the same thing I naively did. Clarifying the documentation that only posts knitted with `distill::distill_article` output format can be imported from elsewhere (is this correct?)
@jjallaire, would it be worth adding an informative error message if the url provided points to a non-distill article?
> clarify docs on import_post function

- DESCRIPTION
- NEWS.md
- R/distill_article.R
- man/distill_article.Rd
This will close #359 
In **rmarkdown**, `css` argument is now handled directly in `html_document_base` and will by default process any `.scss` or `.sass` file with `sass::sass()` when **sass** 📦 is available. 
If a `.css` it will pass it as-is to Pandoc argument. If a `.scss` or `.sass` it will be processed by `sass::sass()` to compile `.css` file than will be used as Pandoc's arg.
@apreshill you're example should work now
````markdown
---
title: "Untitled"
date: 2020-12-18
output: 
distill::distill_article: 
css: styles.scss
---
```{cat, engine.opts = list(file = "style.scss")}
$green: #212D2C;
$sky: #A9FDFF;
$cyan: #36C9B4;
.my-color {
background-color: $green;
color: $sky;
padding: 1em;
}
.my-link a {
@extend .my-color;
color: $cyan;
&:hover {
background-color: rgba( $green, .5 ); …
> let `html_document_base()` handle css argument

- NEWS.md
- R/navigation.R
close #377
Error was cause by nodes with attributes having no values, which valid in HTML but not in XML
````markdown
tmp <- tempfile()
xfun::write_utf8(
'<script async defer data-domain="koaning.io" src="https://plausible.io/js/plausible.js"></script>',
tmp)
xml2::read_xml(tmp)
#> Error in read_xml.character(tmp): Specification mandates value for attribute async [41]
xml2::read_html(tmp)
#> {html_document}
#> <html>
#> [1] <head>\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8 ...
unlink(tmp)
````
> Use `read_html()` on `_footer.html`

- NEWS.md
- R/sitemap.R
Fix #376
At least one issue is a change in rmarkdown 2.8 that broke it, but it may not be the only issue. We'll see.
> Fix RSS feed with full content 

- NEWS.md
- inst/rmarkdown/templates/distill_article/resources/default.html
**distill** does not currently have the CSS rules inserted by Pandoc for the references part created by citeproc 
https://github.com/jgm/pandoc/blob/06408d08e5ccf06a6a04c9b77470e6a67d98e52c/data/templates/styles.html#L157-L180
This will be inserted now in the template when `--citeproc` is used, and it will apply on the div and other parts created by Pandoc for references.
Test file
````markdown
---
title: "About"
bibliography: packages.bib
csl: https://www.zotero.org/styles/nature-communications
output: distill::distill_article
---
```{r, include = FALSE}
knitr::write_bib(c("rmarkdown", "knitr"), "packages.bib")
```
See knitr [@knitr2014] and rmarkdown @R-rmarkdown
````
This deals with one feedback in #392
> Add CSS code in template for new citeproc style

- NEWS.md
- R/collections.R
> Add `aria-label` and `aria-hidden` to sharing icons

- DESCRIPTION
- NEWS.md
- R/metadata.R
It won't have the expected effect when the connection already specify `encoding = UTF-8`. 
The `encoding` argument in `readLines()` seems only useful when the connection to the file is not yet opened.
This fixes #436
> do not specify encoding in readLines() when reading from connection

- NEWS.md
- inst/rmarkdown/templates/distill_article/resources/distill.html
This fixes #423 
When a note style CSL is used, Pandoc will create a footnote for this reference. _distill.js_ will then handle this as a regular footnote and create a tooltip on hover. After that, **distill** R package will create a tooltip for the reference as it is a feature with any CSL. 
This creates a double tooltip on hover. 
This PR specifically handle the `d-footnote` element in the reference Span when citation are processed by **distill**.
The `d-footnote` is removed in the post process and replaced by usual tooltip with reference content.
> Remove distill footnote tooltip when a note style CSL is used

- DESCRIPTION
- NEWS.md
- R/navigation.R
When processing rendered footer, be sure to read as UTF-8
This close #417
> Correct encoding support in _footer.html insertion

- DESCRIPTION
- NEWS.md
- R/sitemap.R
Fixes #454 
It seems we had a hidden issue in our workflow that has been unveiled by the fact you two posts with same end of name are found among the project post. This creates unhandled conflict. I think my fix will solves this. 
The whole RSS feed process should be rethink IMO (https://github.com/rstudio/distill/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+RSS)
> Correctly find the Rmd article source for the full content feed

- DESCRIPTION
- NEWS.md
- inst/rmarkdown/templates/distill_article/resources/distill.html
fix #286. This seems possible as width is also set / unset in JS for knitr plot output
https://github.com/rstudio/distill/blob/0e06b3f7d2b3aafcdb0f3038b6573330df2d45dc/inst/rmarkdown/templates/distill_article/resources/distill.html#L1285-L1296
This way the CSS rule would not take precedence over a CSS style value set on image using `out.width`
> Remove CSS rule so that `out.width` can be applied on a chunk

- DESCRIPTION
- NEWS.md
- R/collections.R
- tests/testthat/helpers.R
- tests/testthat/test-collections.R
- tests/testthat/test-create.R
- tests/testthat/test-distill_article.R
This should fix #425 
We were inserting every content text in the `search.json` which is too much and makes website slow.
> <script> and <style> are correctly ignored from search content

- DESCRIPTION
- NEWS.md
- R/metadata.R
When pandoc fails to parse the year of a bibliography entry it creates an empty `issued$date-parts`.
This PR improves the check for the availability of `publication_date` metadata entry to work in these scenarios.
Example bib which currently errors (but is fixed with this change):
```
@Misc{gentleman,
author={Robert Gentleman and Duncan {Temple Lang}},
title={Statistical Analyses and Reproducible Research},
year={May 2004},
howpublished={Bioconductor Project Working Papers},
number=2
}
```
> Fix citation metadata for invalid bib year entry

- DESCRIPTION
- NEWS.md
- R/create.R
- R/import.R
- R/utils.R
- tests/testthat/test-utils.R
this is because R 4.3.0 deprecated the format argument.
`as.character.POSIXt` as already passing to `format()` so this should be backward compatible
closes #488
> Use format() instead of as.character()

- DESCRIPTION
- NEWS.md
- inst/rmarkdown/templates/distill_article/resources/default.html
> Add support for a subtitle field placed directly under title

- NEWS.md
- R/publish.R
- R/sitemap.R
- R/utils.R
- man/publish_website.Rd
NULL in R gives empty list in JSON (when read back). Testing for NULL was not correct to default for `title` when no `description` is provided.
This is now handled correctly and should avoid cryptic error from XML writing. Fix #490 and fix #448
The code base is from several years ago, so it is surprising that this was never reported before. Probably a non empty `description` has always been provided. 🤷
> handle empty description in articles json when creating the XML feed
